# Generated by Django 3.2 on 2021-04-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
