# Generated by Django 3.2 on 2021-04-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propellers', '0003_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('product_id', models.CharField(max_length=64)),
                ('old_Serial', models.CharField(blank=True, max_length=64)),
                ('new_Serial', models.CharField(blank=True, max_length=64)),
                ('hub_Serial', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('do_not_import', models.CharField(blank=True, max_length=64)),
                ('hub_model', models.CharField(blank=True, max_length=64)),
                ('blade_count', models.CharField(blank=True, max_length=64)),
                ('blade_model', models.CharField(blank=True, max_length=64)),
                ('bld_dia', models.CharField(blank=True, max_length=64)),
                ('taper', models.CharField(blank=True, max_length=64)),
                ('rotation', models.CharField(blank=True, max_length=64)),
                ('taper_specs', models.CharField(blank=True, max_length=64)),
                ('nickel_LE', models.CharField(blank=True, max_length=64)),
                ('tip_color', models.CharField(blank=True, max_length=64)),
                ('weight_start', models.CharField(blank=True, max_length=64)),
                ('weight_end', models.CharField(blank=True, max_length=64)),
                ('weight_vert', models.CharField(blank=True, max_length=64)),
                ('weight_taperbefore', models.CharField(blank=True, max_length=64)),
                ('weight_taperafter', models.CharField(blank=True, max_length=64)),
                ('tracking', models.CharField(blank=True, max_length=64)),
                ('bld_notes', models.CharField(blank=True, max_length=64)),
                ('pinned_collars', models.CharField(blank=True, max_length=64)),
                ('customer_id', models.CharField(blank=True, max_length=64)),
                ('customer_notes', models.CharField(blank=True, max_length=64)),
                ('vehicle_id', models.CharField(blank=True, max_length=64)),
                ('vehicle_notes', models.CharField(blank=True, max_length=64)),
                ('engine_id', models.CharField(blank=True, max_length=64)),
                ('engine_notes', models.CharField(blank=True, max_length=64)),
                ('bolt_pattern', models.CharField(blank=True, max_length=64)),
                ('bolt_pattern_notes_new_field', models.CharField(blank=True, max_length=64)),
                ('reduction_ratio_rename_to_red_drive_name', models.CharField(blank=True, max_length=64)),
                ('reduction_style', models.CharField(blank=True, max_length=64)),
                ('update_1_date', models.CharField(blank=True, max_length=64)),
                ('update_1', models.CharField(blank=True, max_length=64)),
                ('update_2_date', models.CharField(blank=True, max_length=64)),
                ('update_2', models.CharField(blank=True, max_length=64)),
                ('update_3_date', models.CharField(blank=True, max_length=64)),
                ('update_3', models.CharField(blank=True, max_length=64)),
                ('update_4_date', models.CharField(blank=True, max_length=64)),
                ('update_4', models.CharField(blank=True, max_length=64)),
                ('update_5_Date', models.CharField(blank=True, max_length=64)),
                ('update_5', models.CharField(blank=True, max_length=64)),
                ('x_studio_ship_date', models.CharField(blank=True, max_length=64)),
                ('old_notes', models.CharField(blank=True, max_length=64)),
                ('old_bldspecs', models.CharField(blank=True, max_length=64)),
                ('old_bldnum', models.CharField(blank=True, max_length=64)),
                ('old_bldtype', models.CharField(blank=True, max_length=64)),
                ('old_hub', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
